### ISSUE TITLE
Prow error flushing action history to GCS: permission issue

### ISSUE THREAD

**Issue by chases2** [sebastienvas/istio-testing#3572]
```
{
insertId: "9ozh6hqz19u2mia4"
jsonPayload: {
component: "tide"
duration: "113.198968ms"
error: "close: googleapi: Error 401: Anonymous caller does not have storage.objects.create access to the Google Cloud Storage object., required"
file: "prow/tide/history/history.go:202"
func: "k8s.io/test-infra/prow/tide/history.(*History).Flush"
level: "error"
msg: "Error flushing action history to GCS."
path: "gs://istio-prow/tide-history.json"
}
```

**Comment by chases2** [comment]
This error is occurring regularly about once a minute

**Comment by listx** [comment]
I don't see this error occurring regularly any more (nothing in the past 3 hours): https://pantheon.corp.google.com/logs/query;query=jsonPayload.component%3D%22tide%22%0A%22Anonymous%20caller%20does%20not%20have%20storage.objects.create%22;timeRange=PT3H;cursorTimestamp=2021-11-11T22:31:48Z?orgonly=true&project=istio-testing&supportedpurview=organizationId&query=%0A. I think we can close this?

EDIT: The search query I used was:
```
jsonPayload.component="tide"
"Anonymous caller does not have storage.objects.create"
```

**Comment by listx** [comment]
I cannot see this any more (nothing in the past day).

I used this search query:

```
resource.type="k8s_container"
resource.labels.cluster_name="prow"
jsonPayload.component="tide"
"Anonymous caller does not have storage.objects.create"
```

/close
