### ISSUE TITLE
Prow fails to deploy on kubernetes v1.22 

### ISSUE THREAD

**Issue by chases2** [sebastienvas/istio-testing#3735]
https://prow.istio.io/view/gs/istio-prow/logs/deploy-prow_test-infra_postsubmit/1476675038076735488

```
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
ingress.extensions/tls-ing configured
error: error retrieving RESTMappings to prune: invalid resource batch/v1, Kind=CronJob, Namespaced=true: no matches for kind "CronJob" in version "batch/v1"
make: *** [Makefile:32: deploy] Error 1
make: Leaving directory '/home/prow/go/src/istio.io/test-infra/prow'
```

**Comment by chases2** [comment]
Second deploy attempt results in a different error message:

https://prow.istio.io/?job=deploy-prow_test-infra_postsubmit
https://prow.istio.io/view/gs/istio-prow/logs/deploy-prow_test-infra_postsubmit/1478494794576564224

```
error validating "cluster/kubernetes-external-secrets_crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "additionalPrinterColumns" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): missing required field "versions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false
```

Need to move the CustomResourceDefinitions back

**Comment by chases2** [comment]
Websearching suggests that a drift in kubectl version might cause a "error retrieving RESTMappings to prune" issue. The cluster is using `1.20.10-gke.1600`; not sure what version the Prow Job (`gcr.io/istio-testing/build-tools:master-2021-12-21T23-55-44`) is using.

**Comment by chases2** [comment]
The cluster version has been updated to v1.22, but that hasn't changed the `api-resources` version of CronJob being used.

https://prow.istio.io/view/gs/istio-prow/logs/deploy-prow_test-infra_postsubmit/1479222668040343552

**Comment by cjwagner** [comment]
This should be fixed now. There is some more context over here: https://github.com/istio/test-infra/issues/3759

/close
