### ISSUE TITLE
slack: periodic jobs missing URL

### ISSUE THREAD

**Issue by howardjohn** [sebastienvas/istio-testing#3759]
![2022-11-01_15-58-30](https://user-images.githubusercontent.com/623453/149040095-0a5f57ed-343b-488f-a327-965af05324f4.png)

Since the format is the same for all job types I am guessing `.Status.URL}` is not set somehow?

**Comment by howardjohn** [comment]
Actually even prow.istio.io has no link, so I guess its not really slack reporting broken but something lower level

**Comment by howardjohn** [comment]
Timing aligns with https://github.com/istio/test-infra/commit/8c51a1111efe7c0fc2e15227970f3fec8669e965 @cjwagner

**Comment by cjwagner** [comment]
I think we accidentally nuked the test-pods namespace (and in the process the deployment job itself) due to calling `kubectl apply` twice with the same pruning resource list.  We may need to use server-side apply for everything or stop using this pruning pattern.
For now I've reverted the change and manually redeployed. Jobs seem to be starting now, e.g. https://prow.istio.io/view/gs/istio-prow/logs/ci-test-infra-branchprotector/1481082039586263040

**Comment by cjwagner** [comment]
I'm not sure why this change didn't cause the ProwJob CRD to be pruned: https://github.com/istio/test-infra/pull/3744
As far as I can tell it should have, but it didn't before or when I ran `make deploy` locally just now.

I'm kind of thinking this pruning logic may be more hazardous than it is worth.

**Comment by howardjohn** [comment]
Does k8s do anything like this or just plain kubectl apply? If so, does it
handle removal of resources at all? I can imagine that needing to remove is
pretty uncommon

**Comment by cjwagner** [comment]
> Does k8s do anything like this or just plain kubectl apply? If so, does it handle removal of resources at all? I can imagine that needing to remove is pretty uncommon

K8s uses bazel to do a `kubectl apply` there is no resource removal. Needing to remove is pretty uncommon and is extremely easy.
The original motivation for the pruning is to help avoid tech debt by ensuring everything in the cluster is checked in. Its a good motivation, but I don't think we really have issues with folks manually applying to the cluster and not checking in the changes any more. I think this pruning mechanism is more often hurting us than helping us in its current form.

**Comment by howardjohn** [comment]
ok, removal sgtm if it's not giving value. If we do want something similar
there are plenty of tools that provide similar behavior in a better way (or
at least different - I don't have a ton of experience with them) such as
kpt, helm, flux, etc. But no need to over engineer it

**Comment by ericvn** [comment]
Removal seems to have put the URL back, but now the job is failing with:
```
Test started yesterday at 7:54 PM failed after 15m0s. (more info)
The pod could not start because it could not mount the volume "oauth": secret "oauth-token" not found
```

**Comment by ericvn** [comment]
The ` ci-prow-autobump` is also failing with the missing token.

**Comment by cjwagner** [comment]
Everything should be fixed now.
Here is a cover for the pitfall: https://github.com/istio/test-infra/pull/3764

/assign
/close
