### ISSUE TITLE
Jobs failing with `could not mount the volume "github": secret "oauth-token" not found`

### ISSUE THREAD

**Issue by ericvn** [sebastienvas/istio-testing#3762]
Several jobs are failing with logs similar to:
```
Test started today at 9:05 AM failed after 15m0s. (more info)
The pod could not start because it could not mount the volume "github": secret "oauth-token" not found
```

This may be a related to the changes noted in https://github.com/istio/test-infra/issues/3759.

**Comment by cjwagner** [comment]
This is a result of https://github.com/istio/test-infra/issues/3750 which I'm working on fixing.

**Comment by cjwagner** [comment]
Should be fixed now. The autobump job has succeeded and branchprotector is chugging along.
/assign
/close
