### ISSUE TITLE
Jobs failing with [Errno 30] Read-only file system: '/etc/rel-pipeline-docker-config/tmp9pdcb698

### ISSUE THREAD

**Issue by ericvn** [sebastienvas/istio-testing#3766]
I see that two jobs:

https://prow.istio.io/job-history/gs/istio-prow/logs/build-base-images_release-builder_release-1.12_periodic

and

https://prow.istio.io/view/gs/istio-prow/logs/build-base-images_release-builder_periodic/1481702742933114880 

have started failing with:

```
gcloud auth configure-docker -q
45
Adding credentials for all GCR repositories.
46
WARNING: A long list of credential helpers may cause delays running 'docker build'. We recommend passing the registry name to configure only the registry you are using.
47
ERROR: (gcloud.auth.configure-docker) Error writing Docker configuration to disk: [Errno 30] Read-only file system: '/etc/rel-pipeline-docker-config/tmp9pdcb698'
```

I'm not sure, but I do notice there was a Prow update PR, https://github.com/istio/test-infra/pull/3740, merged a few hours ago.

**Comment by howardjohn** [comment]
Its a false positive highlighted by regex. The real error is 
```
Error: failed image scan: base image scan of istio/base:2021-10-06T19-01-15 failed. Unable to process exit code:

```

its happened for years. Would be great to fix it

**Comment by ericvn** [comment]
Ah, Should have looked into this further. So the images are now failing a trivy scan (just starting today as I had manually tested this particular one yesterday before they spun the 1.12.2 image..  I'll look into fixing this.

Thanks John.
