### ISSUE TITLE
Missing boskos metrics

### ISSUE THREAD

**Issue by howardjohn** [sebastienvas/istio-testing#3778]
We used to have boskos metrics at http://velodrome.istio.io/. However, this now gives a 502.

https://monitoring.prow.istio.io/ has a bunch of stuff, but no boskos. It would be nice to see the boskos metrics again

**Comment by howardjohn** [comment]
Velodrome is deployed but getting 404 from Google Health check

**Comment by howardjohn** [comment]
```
{"component":"metrics","file":"/go/src/app/cmd/metrics/metrics.go:127","func":"main.handleMetric.func1","handler":"handleMetric","level":"warning","msg":"type must be set in the request.","severity":"warning","time":"2022-01-31T19:38:29Z"}
```

from boskos-metrics

**Comment by howardjohn** [comment]
Boskos is like 2 years old. We need to upgrade probably - not sure how much work that will be though

**Comment by howardjohn** [comment]
Also boskos now seems to be 100% broken now. I think from 1.22 upgrade

**Comment by cjwagner** [comment]
> Also boskos now seems to be 100% broken now. I think from 1.22 upgrade

The only istio cluster that we upgraded to 1.22 was the Prow service cluster which doesn't appear to have any boskos deployments. The build cluster is still at 1.21, is that the cluster you are referring to? I'm guessing yes based on this: https://github.com/istio/test-infra/blob/1067422a1559d3c3fb04cc904c2a0ec7753ca0dc/boskos/Makefile#L19-L20

With respect to boskos metrics and alerts, we have some details about setting that up on the new monitoring stack using terraform here: https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/oss/terraform#boskos-alerts
We do need to configure Workload Metrics in the cluster + a PodMonitor though.

**Comment by howardjohn** [comment]
Ah ok. Then perhaps it's not a 1.22 issue. However, it is broken for some
reason. Metrics had been broken for months and boskos has been entirely
broken for a few days.

**Comment by cjwagner** [comment]
The `boskos-metrics` component has a lot of logs like
> {"component":"metrics","file":"/go/src/app/cmd/metrics/metrics.go:127","func":"main.handleMetric.func1","handler":"handleMetric","level":"warning","msg":"type must be set in the request.","severity":"warning","time":"2022-02-01T01:44:12Z"}

The `boskos-mason` component has logs like:
> E0129 08:12:00.814176       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *crds.DRLCObject: Get https://10.0.0.1:443/apis/boskos.k8s.io/v1/namespaces/boskos/dynamicresourcelifecycles?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: connect: connection refused

I'm assuming this is `boskos-mason` attempting to interact with the build cluster itself which is should have the correct RBAC for: https://github.com/istio/test-infra/blob/1067422a1559d3c3fb04cc904c2a0ec7753ca0dc/boskos/cluster/mason-deployment.yaml#L19
https://github.com/istio/test-infra/blob/1067422a1559d3c3fb04cc904c2a0ec7753ca0dc/boskos/cluster/boskos-deployment.yaml#L17-L48

**Comment by chaodaiG** [comment]
As far as I can tell there are two problems here:

a) Boskos metrics not surfaced. For this issue, as @cjwagner had mentioned, it's recommended to migrate over to https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/oss/terraform#boskos-alerts, @chizhg has experience with setting this up.

b) Boskos stopped working. There was not enough information I could dig from this issue, my guess is that Boskos stopped recycling resources, which could be due to janitor failures. I have inspected janitor log and saw quite a few failures: https://cloudlogging.app.goo.gl/kf4qgd8Ta7sQDuch7. Let me know if you have trouble accessing this issue, I'll create a screenshot for you

**Comment by howardjohn** [comment]
@chaodaiG those logs are from prow-internal, this issue is for the `prow` cluster.
```
resource.type="k8s_container"
resource.labels.project_id="istio-prow-build"
resource.labels.namespace_name="boskos"
resource.labels.container_name="boskos"
severity=ERROR
```

**Comment by chaodaiG** [comment]
you are right, that was a wrong link. Inspecting `prow` cluster and it also has the same error https://cloudlogging.app.goo.gl/1ryxri5TdbMZscyT7

**Comment by chaodaiG** [comment]
> you are right, that was a wrong link. Inspecting `prow` cluster and it also has the same error https://cloudlogging.app.goo.gl/1ryxri5TdbMZscyT7

@howardjohn , @chizhg please take a look

**Comment by howardjohn** [comment]
As a first step should we update boskos? Its almost 2 years old. Since its auth errors could be related to the WI changes we made recently

**Comment by chaodaiG** [comment]
> As a first step should we update boskos? Its almost 2 years old. Since its auth errors could be related to the WI changes we made recently

sounds like a good idea to me

**Comment by howardjohn** [comment]
Who owns this?

**Comment by chaodaiG** [comment]
The team that owns prow is in the process of providing minimal maintenance of Boskos repo. Users are still responsible for managing their own deployment

**Comment by howardjohn** [comment]
Who are "users" in this context? We have a very fuzzy line from "Istio engineers", "Google Istio engineers", "Google Istio engineers that sometimes work on test related things" to "Google Prow team". I don't know where the lines are nor where this falls. Can we assign to a concrete individual?

**Comment by zirain** [comment]
any update about this?

**Comment by upodroid** [comment]
Drive by comment:

@howardjohn I recently fixed this for Knative at https://github.com/knative/test-infra/pull/3360. Grab the new PodMonitoring code from oss-test-infra repo and make sure the boskos deployment has the metrics port defined. Spend a good 20 minutes  debugging unavailable metrics in Managed Prometheus.

**Comment by howardjohn** [comment]
We are not using boskos now
